site:
  name: samperalabs
  site: 'https://samperalabs.com'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId:

# Default SEO metadata
metadata:
  title:
    default: Bernat Sampera - AI Integration Specialist
    template: '%s â€” samperalabs'
  description: 'Integrating AI solutions into your websites and applications. Helping businesses leverage artificial intelligence technology for better user experiences.'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: samperalabs
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@bernatsampera'
    site: '@samperalabs'
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: 'lofi' # Values: "system" | "light" | "dark" | "light:only" | "only"
